module.exports = {
    MISSING_EMAIL: 'MISSING_EMAIL',
    CANNOT_FIND_USER: 'CANNOT_FIND_USER',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    EMAIL_EXISTED: 'EMAIL_EXISTED',
    INVALID_SIGN_UP_INFO: 'INVALID_SIGN_UP_INFO',
    CANNOT_UPDATE_USER: 'CANNOT_UPDATE_USER',
    INVALID_JOB_INFO: 'INVALID_JOB_INFO',
    CANNOT_FIND_JOB: 'CANNOT_FIND_JOB',
    INVALID_CATEGORY_INFO: 'INVALID_CATEGORY_INFO',
    NAME_CATEGORY_EXISTED: 'NAME_CATEGORY_EXISTED'   
}